// Halaman utama
export const CHANGE_STATE_HALAMAN_UTAMA = "CHANGE_STATE_HALAMAN_UTAMA";
export const SUCCESS_GET_COMPETITIONS = "SUCCESS_GET_COMPETITIONS";

// Papan Klasemen
export const CHANGE_STATE_PAPAN_KLASEMEN = "CHANGE_STATE_PAPAN_KLASEMEN";
export const SUCCESS_GET_PAPAN_KLASEMEN = "SUCCESS_GET_PAPAN_KLASEMEN";

// Jadwal Pertandingan
export const CHANGE_STATE_JADWAL_PERTANDINGAN =
  "CHANGE_STATE_JADWAL_PERTANDINGAN";
export const SUCCESS_GET_JADWAL_PERTANDINGAN =
  "SUCCESS_GET_JADWAL_PERTANDINGAN";
